# Generated by Django 5.0.6 on 2024-05-31 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
