# Generated by Django 5.0.6 on 2024-07-19 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_price_product_unit_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title']},
        ),
    ]
